# Generated by Django 4.2.7 on 2023-11-03 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, validators=[django.core.validators.MinLengthValidator(4)])),
                ('job_title', models.TextField(max_length=200, validators=[django.core.validators.MinLengthValidator(14)])),
                ('password', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(6)])),
            ],
        ),
    ]
